---
# vars.yml - compose-configs/frigate

## Infisical-stored secrets
vault_app_frigate_rtsp_password: "{{ lookup('infisical', 'vault_app_frigate_rtsp_password', path='/apps') }}"
vault_app_frigate_nfs_options: "{{ lookup('infisical', 'vault_app_frigate_nfs_options', path='/apps') }}"
vault_app_frigate_nfs_device: "{{ lookup('infisical', 'vault_app_frigate_nfs_device', path='/apps') }}"
## End

frigate_name: "frigate"
frigate_image: "ghcr.io/blakeblackshear/frigate:stable"
frigate_shm_size: "384mb"
frigate_webui_port: "8971"
frigate_rtsp_port: "8554"
frigate_webrtc_port: "8555"
