---
# deploy-gotify.yml

- name: Deploy Gotify
  hosts: homelab
  become: true

  vars_files:
    - ../compose-configs/gotify/vars.yml

  roles:
    - role: docker-compose-app
      vars:
        app_name: gotify
        env_template: .env.j2
