---
# deploy-frigate.yml

- name: Deploy Frigate
  hosts: homelab
  become: true

  vars_files:
    - ../compose-configs/frigate/vars.yml
  roles:
    - role: docker-compose-app
      vars:
        app_name: frigate
        env_template: .env.j2
