---
# main.yml

qbittorrent_settings_base_path: "{{ docker_compose_base_dir }}/qbittorrent"
qbittorrent_settings_config_path: "{{ qbittorrent_settings_base_path }}/config/qBittorrent"
qbittorrent_settings_themes_path: "{{ qbittorrent_settings_base_path }}/themes"
