---
# requirements.yml

collections:
  - name: community.general
    version: ">=11.0.0"
  - name: community.docker
    version: ">=4.0.0"
  - name: ansible.posix
    version: ">=2.0.0"
  - name: prometheus.prometheus
    version: ">=0.27.0"
  - name: grafana.grafana
    version: ">=6.0.0"
  - name: infisical.vault
    version: ">=1.2.0"
